language: php

php:
    - 5.3

env:
 - DB=MYSQL CORE_RELEASE=3.1
 - DB=SQLITE CORE_RELEASE=3.1

matrix:
  include:
    - php: 5.4
      env: DB=MYSQL CORE_RELEASE=3.1

before_script:
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss
  - "if [ -d silverstripe-wordpressimport ]; then mv silverstripe-wordpressimport wordpressimport; fi;"

script: 
 - phpunit wordpressimport/tests/